version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8090:8090"
    depends_on:
      - chat-service
    networks:
      - app-network

  chat-service:
    build: ./chat-service
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      LOG_LEVEL: DEBUG
    depends_on:
      - postgres
    expose:
      - "5000"
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
